name: metadata file schema
desc: This is the schema of the metadata file, please refer to https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/METADATA.md for more info.
type: map
mapping:
    'team_name':
        required: True
    'team_abbr':
        required: True
        range:
            max: 15
    'model_name':
        required: True
        type: str
    'model_contributors':
        required: True
        type: str
    'model_abbr':
        required: True
        type: str
        range:
            max: 15
    'website_url':
        required: True
        type: str
        pattern: ^((https?):\/\/)?(www.)?[a-z0-9]+\.[a-z]+(\/[a-zA-Z0-9#]+\/?)*$
    'license':
        required: True
        type: str
    'team_model_designation':
        required: True
        type: str
        example: This should be one of \"primary\", \"secondary\", \"proposed\" or \"other\"
        enum: ['primary', 'secondary', 'proposed', 'other']
    'methods':
        required: True
        type: str
        range:
            max: 200
    'repo_url':
        type: str
        pattern: ^((https?):\/\/)?(www.)?[a-z0-9]+\.[a-z]+(\/[a-zA-Z0-9#]+\/?)*$
    'this_model_is_an_ensemble':
        type: str
    'citation':
        type: str
        pattern: ^((https?):\/\/)?(www.)?[a-z0-9]+\.[a-z]+(\/[a-zA-Z0-9#]+\/?)*$
    'institution_affil':
        type: str
    'team_funding':
        type: str
    'twitter_handles':
        type: str
    'data_inputs':
        type: str
    'methods_long':
        type: str
        

    