# Items used for branding
branding:
  title: "CDC COVID-19 ILI Forecasting Project"
  parent: ""
  description: "CDC COVID-19 influenza-like illness (ILI) Forecasting Project"
  imageUrl: ""
  aboutUrl: "http://reichlab.io/2017/11/28/flusight-ensemble.html"
  appUrl: ""
  sourceUrl: "https://github.com/cdcepi/COVID-19-ILI-forecasting-submissions"
  parentUrl: "https://github.com/cdcepi/COVID-19-ILI-forecasting/blob/master/templates-and-data/covid-19-ili-forecast-guidance.pdf"
