# Items used for branding
branding:
  title: "Reich Lab"
  parent: ""
  description: "COVID-19 Forecasts - Cumulative Deaths"
  imageUrl: ""
  aboutUrl: "https://github.com/reichlab/covid19-forecast-hub"
  appUrl: ""
  sourceUrl: "https://github.com/reichlab/covid19-forecast-hub"
  parentUrl: "https://github.com/reichlab/covid19-forecast-hub"
