# Items used for branding
branding:
  title: "COVID-19 Cumulative Death Forecasts"
  parent: ""
  description: "COVID-19 Death Forecasting Project"
  imageUrl: ""
  aboutUrl: "https://github.com/reichlab/covid19-death-forecasts"
  appUrl: ""
  sourceUrl: "https://github.com/reichlab/covid19-death-forecasts"
  parentUrl: "https://github.com/reichlab/covid19-death-forecasts"
